### ISSUE TITLE
ndmf's generated animators break child animators

### ISSUE THREAD

**Issue by Sergster1** [bdunderscore/ndmf#163] opened 2024-02-08 20:32 UTC
I ran into an issue with ndmf on a new Unity 2022 project where ndmf generates animators on avatars that are not using ndmf functions and causes adverse effects. You can test this with [hfcRed's among us prefab](https://github.com/hfcRed/Among-Us-Follower) as the ndmf generated animator breaks the transition from idle to run. It also appears to remove zero-weight bones that are not a physbone component.

Steps to reproduce:

1. Create a new 2022 Avatar Project with ndmf imported via VCC
2. Import hfcRed's among us follower prefab
3. Enter play mode

Result:
ndmf's cloned animators conflict with the intended behavior. Bones that are zero weight and present in the Edit Scene are removed in play mode.

Expected Outcome:

Animators cloned by ndmf should function as originally intended. Unless specified, bones should not be removed from an avatar at any time. 

Temporary Mitigation:
Removing ndmf from my project resolves the issue

Once I get a chance I can film a video showing the bug if you are unable to reproduce it.

**Comment by bdunderscore** [comment] 2024-02-12 05:47
This bug appears to have been caused by some logic to recreate animators in Apply on Play added to work around another issue with Gesture Manager, and can be fixed by reversing the order in which animators are recreated. It'll be fixed in 1.6.2.

Note that cloning animators, as well as deleting empty bones, were unrelated to this issue. If you have specific problems with these behaviors, please open a new issue with a detailed description of what you're trying to achieve, and how these processes interfered with it.

In particular, for the empty bone deletion case - this was put in because certain MA features result in a bunch of garbage empty game objects being left behind, which needed cleaning up. As such, I want to understand _why_ people want to retain bones, so I can improve the automation here to address that use case, rather than simply disabling this optimization entirely.

**Comment by bdunderscore** [comment] 2024-02-12 05:50
Also note that this bug only appears to impact Apply on Play mode, so it should still work on upload.

**Closed** 2024-02-12 11:01 UTC
