### ISSUE TITLE
Invalidateing `ComputeContext` of `IRenderFilter.Process` does not trigger refresh

### ISSUE THREAD

**Issue by anatawa12** [bdunderscore/ndmf#259] opened 2024-06-10 01:02 UTC
Invalidateing `ComputeContext` of `IRenderFilter.Process` does not trigger refresh.

I tried to implement `IRenderFilter` for AAO RemoveMesh by Mask but I could not find way to refresh / recreate the mesh.

I added the following code to check if `context` is invalidated expected time and context is invalidated at expected timing but it looks invalidating the context triggers nothing.

```
context.OnInvalidate.ContinueWith(_ => Debug.Log("context.OnInvalidate.ContinueWith"));
```

https://github.com/anatawa12/AvatarOptimizer/blob/209e6e58eeade1c69cbed7878b067914023b854e/Editor/Processors/EditSkinnedMeshComponentRendererFilter.cs

**Comment by bdunderscore** [comment] 2024-06-10 01:57
Thanks for the report - I'll take a look probably closer to next weekend - there's a world project I need to work on first unfortunately.

**Comment by bdunderscore** [comment] 2024-06-13 03:09
Is this fixed by https://github.com/bdunderscore/ndmf/pull/262 ? I'm not able to reproduce the issue with this change (changes in MaskTextureEditor are immediately applied)

**Comment by bdunderscore** [comment] 2024-06-13 03:12
(I'm using your ndmf-preview-system branch)

**Comment by bdunderscore** [comment] 2024-06-13 03:14
Nevermind, I was using the wrong branch (two checkouts...). Issue reproed, looking...

**Comment by bdunderscore** [comment] 2024-06-13 03:28
The issue appears to be that ObjectChangeEventStream events aren't being issued for your texture edits. This is because they're not registered in the normal unity Undo system (probably for good reason...)

Here's my plan:
- I'll add an API to manually trigger change events
- I'll add asset update callbacks to catch external file updates (which don't trigger ObjectChangeEventStream it seems...?)
- I'll also add a periodic fallback check based on the texture hash.

**Comment by bdunderscore** [comment] 2024-06-13 03:49
Also: ComputeContext isn't using a long-lived object as its target token when being called from PreviewPipeline.

**Comment by anatawa12** [comment] 2024-06-13 03:53
> The issue appears to be that ObjectChangeEventStream events aren't being issued for your texture edits. This is because they're not registered in the normal unity Undo system (probably for good reason...)

Not triggering refresh while editing image with texture editor is intended.
It does not change the texture on the `EditSkinnedMeshComponentRendererFilter` component and retrieving intermediate (editing) texture from texture editor is not yet implemented.

Not triggering refresh with save button on texture editor is not intended.
It will replace the png file and `AssetDatabase.ImportAsset` so it should mean NDMF preview system is not triggered on external asset changes I think.

---

the `EditSkinnedMeshComponentRendererFilter` will observe the RemoveMeshByMask component so changing the component itself should trigger refresh

---

I'll try #262

**Comment by bdunderscore** [comment] 2024-06-13 03:57
I've reproed the issue locally, so I think I can debug this from here. Thanks for the report!

**Closed** 2024-06-16 22:57 UTC
